### ISSUE TITLE
Integrate macaroons 

### ISSUE THREAD

**Issue by Toshbrown** [me-box/databox-store-blob#4]
Macaroons need to be supported and checked with the arbiter for all endpoints.

**Comment by yousefamar** [comment]
Just wanted to ask thoughts on an implementation detail for these caveats:

To recap, the conversion is to something sum-of-products like, where the expression to satisfy is the logical AND of all caveats. So things that are logical OR, like a whitelist of paths, are contained within one caveat (path can be an array of strings as well as a string).

Right now, timestamp for checking expiry is not implemented in the above PR, but once implemented the same way, that would thus mean that a macaroon without it would be rejected since we check for it (as opposed to allowing it, as you might expect).

So should macaroons with any missing caveats be rejected, or should only some be required? (The latter would allow the existence of "god-macaroons" with e.g. only `target` and can't expire, or can use any path, or what have you).

**Comment by Toshbrown** [comment]
I have merged pr #11 into the new macaroons branch. I'm just deploying a new image to test it.

For now, for simplicity and safety, I would reject if caveats are missing. If we want long lived macaroons we can set the expiry to be far into the future ;-) We should probably discuss the finer details of the implementation with the rest of the team when we have nailed down some of the use-cases. 

I'm also using this as an opportunity to refactor the code and make a lib dir. Long term this can be moved into a separate repo to help with sharing code between components etc. 

I've created a databox-request module that wraps up the HTTPs ca changes and a few other things.

**Comment by yousefamar** [comment]
Sounds good, thanks! It looks like you brought everything up to date, right? If so, that's good news because merge tools are WMDs in my hands and that means I won't have to. :) Thanks for fixing the request in macaroon-verifier too; completely slipped my mind.

**Comment by Toshbrown** [comment]
Yep, all merged and ready to go.  Think I may have filled the disk on amar.io though ;-( sorry.

Some of these images are needlessly large. Now you have moved to ursa-purejs we can use node:alpine as the base for the images saving around 500Mb per container. Which is nice!

**Comment by Toshbrown** [comment]
Implemented in #18
